In [9]:
import torch
from torch.distributions import Gumbel

gumbel_distr = Gumbel(torch.tensor([0.1,0.2]),1)

In [20]:
x = gumbel_distr.sample()
x

tensor([1.2462, 1.1979])

In [21]:
Z = -float('inf')

tensor([-inf])

In [32]:
torch.cat((x, torch.tensor([Z])))

tensor([1.2462, 1.1979,   -inf])

In [33]:
max_value = torch.max(torch.cat((x, torch.tensor([Z]))))
print(max_value)

tensor(1.2462)
