In [4]:
import torch
from torch.distributions import Gumbel

gumbel_distr = Gumbel(torch.tensor([0.,0.]),1)

In [3]:
x = gumbel_distr.sample()
x

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [21]:
Z = -float('inf')

In [ ]:
y_s_prime = torch.cat([seq, torch.tensor([[token_id]])], dim=1)

tensor([-inf])

In [32]:
seq = torch.tensor([[1, 2, 3, 4, 5]])
seq.shape


torch.Size([1, 5])

In [35]:
V = 52000
tokens = torch.ones((V,))
tokens.shape

torch.Size([52000])

In [ ]:
seq  1
seq  2
seq  3
seq  4

In [42]:
import torch

seq = torch.tensor([[1, 2, 3, 4, 5]])  # Shape: (1, 5)
V = 52000
tokens = torch.ones((V,))             # Shape: (52000,)

# Choose how many tokens you want to stack with
N = 4  # For example, use first 4 tokens

# Repeat seq N times and reshape
seq_repeated = seq.repeat(V, 1)       # Shape: (N, 5)

# Select N tokens and reshape to column vector
tokens_slice = tokens.unsqueeze(1)  # Shape: (N, 1)

# Concatenate along last dimension
stacked = torch.cat([seq_repeated, tokens_slice], dim=1)  # Shape: (N, 6)

print(stacked)


tensor([[1., 2., 3., 4., 5., 1.],
        [1., 2., 3., 4., 5., 1.],
        [1., 2., 3., 4., 5., 1.],
        ...,
        [1., 2., 3., 4., 5., 1.],
        [1., 2., 3., 4., 5., 1.],
        [1., 2., 3., 4., 5., 1.]])


In [32]:
torch.cat((x, torch.tensor([Z])))

tensor([1.2462, 1.1979,   -inf])

In [33]:
max_value = torch.max(torch.cat((x, torch.tensor([Z]))))
print(max_value)

tensor(1.2462)


In [43]:
import torch

V = 52000
A = torch.randn(V, 4)          # (V, 4)
B = torch.arange(V).float()    # (V,)
C = torch.arange(1000, V+1000).float()  # (V,)

# Stack B and C into (V, 2)
BC = torch.stack([B, C], dim=1)  # (V, 2)

# Concatenate with A
merged = torch.cat([A, BC], dim=1)  # (V, 6)

# Reshape to (V, 6, 1, 1)
final = merged.unsqueeze(2).unsqueeze(3)  # (V, 6, 1, 1)

print(final.shape)  # torch.Size([52000, 6, 1, 1])


torch.Size([52000, 6, 1, 1])


In [47]:
x = [[torch.tensor([1, 2, 3])],[ torch.tensor([4, 5, 6])]]
torch.stack(x).shape

TypeError: expected Tensor as element 0 in argument 0, but got list

In [60]:
a = torch.zeros((52000,5))
b = torch.zeros((52000,1))
c = torch.zeros((52000,1))

torch.stack([a,b,c], dim=1).shape

RuntimeError: stack expects each tensor to be equal size, but got [52000, 5] at entry 0 and [52000, 1] at entry 1

In [ ]:
a = torch.zeros((3,52000,6))

In [ ]:
a[:,:,-1].shape

torch.Size([3, 52000, 6])